# Generated by Django 5.1.6 on 2025-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
